name: Build and deploy Python app to Azure Web App - chatTest-backend-a

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Optional: install dependencies & run tests locally (good for CI)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add test step if you have tests
      # - name: Run tests
      #   run: pytest

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatTest-backend-a'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8E7A4E85A5414384992F9B2BAD0C580F }}
          package: .
